name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Lint v1-very-simple
      run: (cd v1-very-simple; go vet ./...)

    - name: Lint v2-domain-adapters-and-helpers
      run: (cd v2-domain-adapters-and-helpers; go vet ./...)

    - name: Test v1-very-simple
      run: (cd v1-very-simple; go test ./...)

    - name: Test v2-domain-adapters-and-helpers
      run: (cd v2-domain-adapters-and-helpers; go test ./...)
