name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Lint v1-very-simple
      run: (cd v1-very-simple; go vet ./...)

    - name: Lint v1-simple-with-short-interface-names
      run: (cd v1-simple-with-short-interface-names; go vet ./...)

    - name: Test v1-very-simple
      run: (cd v1-very-simple; go test ./...)

    - name: Test v1-simple-with-short-interface-names
      run: (cd v1-simple-with-short-interface-names; go test ./...)
